CREATE DATABASE `COLLATE_test1` CHARACTER SET=gbk COLLATE=gbk_chinese_ci;
USE COLLATE_test1;
CREATE TABLE t1(
	n CHAR(2)
);
INSERT INTO t1 VALUES ('a'),('B'),('c');
SELECT * FROM t1 ORDER BY n;

CREATE DATABASE `COLLATE_test2` CHARACTER SET=gbk COLLATE=gbk_bin;
USE COLLATE_test2;
CREATE TABLE t1(
	n CHAR(2)
);
INSERT INTO t1 VALUES ('a'),('B'),('c');
SELECT * FROM t1 ORDER BY n;